svn path=/trunk/; revision=89

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -707,12 +707,11 @@ HAVE_MAN2HTML
 COMPILER_VERSION
 CPP
 EGREP
+MOC
 PKG_CONFIG
 IPV6_TRUE
 IPV6_FALSE
-QT_CFLAGS
 QT_LIBS
-MOC
 GUI_TRUE
 GUI_FALSE
 POP_TRUE
@@ -763,9 +762,7 @@ CXX
 CXXFLAGS
 CCC
 CPP
-PKG_CONFIG
-QT_CFLAGS
-QT_LIBS'
+PKG_CONFIG'
 
 
 # Initialize some variables set by options.
@@ -1396,8 +1393,6 @@ Some influential environment variables:
   CXXFLAGS    C++ compiler flags
   CPP         C preprocessor
   PKG_CONFIG  path to pkg-config utility
-  QT_CFLAGS   C compiler flags for QT, overriding pkg-config
-  QT_LIBS     linker flags for QT, overriding pkg-config
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -6569,6 +6564,65 @@ _ACEOF
 	fi
 
 
+	MOC="${e_qtmoc}"
+	# Extract the first word of "moc", so it can be a program name with args.
+set dummy moc; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_MOC+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $MOC in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_MOC="$MOC" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_MOC="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+MOC=$ac_cv_path_MOC
+if test -n "$MOC"; then
+  { echo "$as_me:$LINENO: result: $MOC" >&5
+echo "${ECHO_T}$MOC" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+
+	if test "$MOC" != ""
+	then
+		{ echo "$as_me:$LINENO: checking moc is for qt 4" >&5
+echo $ECHO_N "checking moc is for qt 4... $ECHO_C" >&6; }
+		if test x$GREP = x ; then GREP=grep ; fi
+		if test -x "$MOC" -a "`$MOC -v 2>&1 | $GREP 'Qt 4'`" != "" ; then
+			{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+			aclocal_moc="$MOC"
+		else
+			{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+			aclocal_moc=""
+		fi
+	fi
+
+
 
 
 if test "x$ac_cv_env_PKG_CONFIG_set" != "xset"; then
@@ -6748,146 +6802,21 @@ if test "${enable_gui+set}" = set; then
 fi
 
 
-	qt4="no"
-	qt4moc="no"
 	if test "$enable_gui" = "no"
 	then
-		:
+		MOC=""
 	else
-
-pkg_failed=no
-{ echo "$as_me:$LINENO: checking for QT" >&5
-echo $ECHO_N "checking for QT... $ECHO_C" >&6; }
-
-if test -n "$PKG_CONFIG"; then
-    if test -n "$QT_CFLAGS"; then
-        pkg_cv_QT_CFLAGS="$QT_CFLAGS"
-    else
-        if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"QtGui >= 4.0.1\"") >&5
-  ($PKG_CONFIG --exists --print-errors "QtGui >= 4.0.1") 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; then
-  pkg_cv_QT_CFLAGS=`$PKG_CONFIG --cflags "QtGui >= 4.0.1" 2>/dev/null`
-else
-  pkg_failed=yes
-fi
-    fi
-else
-	pkg_failed=untried
-fi
-if test -n "$PKG_CONFIG"; then
-    if test -n "$QT_LIBS"; then
-        pkg_cv_QT_LIBS="$QT_LIBS"
-    else
-        if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"QtGui >= 4.0.1\"") >&5
-  ($PKG_CONFIG --exists --print-errors "QtGui >= 4.0.1") 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; then
-  pkg_cv_QT_LIBS=`$PKG_CONFIG --libs "QtGui >= 4.0.1" 2>/dev/null`
-else
-  pkg_failed=yes
-fi
-    fi
-else
-	pkg_failed=untried
-fi
-
-
-
-if test $pkg_failed = yes; then
-
-if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
-        _pkg_short_errors_supported=yes
-else
-        _pkg_short_errors_supported=no
-fi
-        if test $_pkg_short_errors_supported = yes; then
-	        QT_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "QtGui >= 4.0.1"`
-        else
-	        QT_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "QtGui >= 4.0.1"`
-        fi
-	# Put the nasty error message in config.log where it belongs
-	echo "$QT_PKG_ERRORS" >&5
-
-	{ echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-                { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-elif test $pkg_failed = untried; then
-	{ echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-else
-	QT_CFLAGS=$pkg_cv_QT_CFLAGS
-	QT_LIBS=$pkg_cv_QT_LIBS
-        { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
-	qt4=yes
-fi
-		if test "$qt4" = "yes"
+		if test "$enable_gui" = "yes" -a "$aclocal_moc" = ""
 		then
-			MOC="${e_qtmoc}"
-			# Extract the first word of "moc", so it can be a program name with args.
-set dummy moc; ac_word=$2
-{ echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_path_MOC+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  case $MOC in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_MOC="$MOC" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_path_MOC="$as_dir/$ac_word$ac_exec_ext"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-IFS=$as_save_IFS
-
-  ;;
-esac
-fi
-MOC=$ac_cv_path_MOC
-if test -n "$MOC"; then
-  { echo "$as_me:$LINENO: result: $MOC" >&5
-echo "${ECHO_T}$MOC" >&6; }
-else
-  { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-fi
-
-
-			{ echo "$as_me:$LINENO: checking moc is for qt 4" >&5
-echo $ECHO_N "checking moc is for qt 4... $ECHO_C" >&6; }
-			if test x$GREP = x ; then GREP=grep ; fi
-			if test -x "$MOC" -a "`$MOC -v 2>&1 | $GREP 'Qt 4'`" != "" ; then
-				{ echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
-				qt4moc="yes"
-			else
-				{ echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-			fi
-		else
-			QT_LIBS=""
-
+			{ echo "$as_me:$LINENO: WARNING: ignoring --enable-gui, set e_qtmoc to a Qt4 moc program to override" >&5
+echo "$as_me: WARNING: ignoring --enable-gui, set e_qtmoc to a Qt4 moc program to override" >&2;}
 		fi
+		MOC="$aclocal_moc"
 	fi
 
-	 if test x$enable_gui != xno -a x$qt4moc = xyes ; then
+
+
+	 if test x$MOC != x ; then
   GUI_TRUE=
   GUI_FALSE='#'
 else
@@ -6895,7 +6824,8 @@ else
   GUI_FALSE=
 fi
 
-	if test x$enable_exec = xno -a x$enable_gui != xno -a x$qt4moc = xyes
+
+	if test x$enable_exec = xno -a x$MOC != x
 	then
 		{ { echo "$as_me:$LINENO: error: using --disable-exec requires --disable-gui" >&5
 echo "$as_me: error: using --disable-exec requires --disable-gui" >&2;}
@@ -7171,13 +7101,12 @@ fi
 	then
 		if test "$with_doxygen" = "yes" -a "$HAVE_DOXYGEN" != "yes"
 		then
-			{ echo "$as_me:$LINENO: WARNING: ignoring --with-doxygen" >&5
-echo "$as_me: WARNING: ignoring --with-doxygen" >&2;}
-		else
-			HAVE_DOXYGEN="$with_doxygen"
-
+			{ echo "$as_me:$LINENO: WARNING: forcing use of doxygen even though not found" >&5
+echo "$as_me: WARNING: forcing use of doxygen even though not found" >&2;}
 		fi
+		HAVE_DOXYGEN="$with_doxygen"
 	fi
+
 
 
 
@@ -7191,13 +7120,12 @@ fi
 	then
 		if test "$with_man2html" = "yes" -a "$HAVE_MAN2HTML" != "yes"
 		then
-			{ echo "$as_me:$LINENO: WARNING: ignoring --with-man2html" >&5
-echo "$as_me: WARNING: ignoring --with-man2html" >&2;}
-		else
-			HAVE_MAN2HTML="$with_man2html"
-
+			{ echo "$as_me:$LINENO: WARNING: forcing use of man2html even though not found" >&5
+echo "$as_me: WARNING: forcing use of man2html even though not found" >&2;}
 		fi
+		HAVE_MAN2HTML="$with_man2html"
 	fi
+
 
 
 
@@ -8310,9 +8238,9 @@ HAVE_MAN2HTML!$HAVE_MAN2HTML$ac_delim
 COMPILER_VERSION!$COMPILER_VERSION$ac_delim
 CPP!$CPP$ac_delim
 EGREP!$EGREP$ac_delim
+MOC!$MOC$ac_delim
 PKG_CONFIG!$PKG_CONFIG$ac_delim
 IPV6_TRUE!$IPV6_TRUE$ac_delim
-IPV6_FALSE!$IPV6_FALSE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -8354,9 +8282,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
-QT_CFLAGS!$QT_CFLAGS$ac_delim
+IPV6_FALSE!$IPV6_FALSE$ac_delim
 QT_LIBS!$QT_LIBS$ac_delim
-MOC!$MOC$ac_delim
 GUI_TRUE!$GUI_TRUE$ac_delim
 GUI_FALSE!$GUI_FALSE$ac_delim
 POP_TRUE!$POP_TRUE$ac_delim
@@ -8396,7 +8323,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 40; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 39; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
