svn path=/trunk/; revision=98

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -707,11 +707,12 @@ HAVE_MAN2HTML
 COMPILER_VERSION
 CPP
 EGREP
-MOC
 PKG_CONFIG
+QT_CFLAGS
+QT_LIBS
+MOC
 IPV6_TRUE
 IPV6_FALSE
-QT_LIBS
 GUI_TRUE
 GUI_FALSE
 POP_TRUE
@@ -762,7 +763,9 @@ CXX
 CXXFLAGS
 CCC
 CPP
-PKG_CONFIG'
+PKG_CONFIG
+QT_CFLAGS
+QT_LIBS'
 
 
 # Initialize some variables set by options.
@@ -1393,6 +1396,8 @@ Some influential environment variables:
   CXXFLAGS    C++ compiler flags
   CPP         C preprocessor
   PKG_CONFIG  path to pkg-config utility
+  QT_CFLAGS   C compiler flags for QT, overriding pkg-config
+  QT_LIBS     linker flags for QT, overriding pkg-config
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -6564,6 +6569,200 @@ _ACEOF
 	fi
 
 
+
+if test "x$ac_cv_env_PKG_CONFIG_set" != "xset"; then
+	if test -n "$ac_tool_prefix"; then
+  # Extract the first word of "${ac_tool_prefix}pkg-config", so it can be a program name with args.
+set dummy ${ac_tool_prefix}pkg-config; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_PKG_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+if test -n "$PKG_CONFIG"; then
+  { echo "$as_me:$LINENO: result: $PKG_CONFIG" >&5
+echo "${ECHO_T}$PKG_CONFIG" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+fi
+if test -z "$ac_cv_path_PKG_CONFIG"; then
+  ac_pt_PKG_CONFIG=$PKG_CONFIG
+  # Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_ac_pt_PKG_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $ac_pt_PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_ac_pt_PKG_CONFIG="$ac_pt_PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_ac_pt_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+ac_pt_PKG_CONFIG=$ac_cv_path_ac_pt_PKG_CONFIG
+if test -n "$ac_pt_PKG_CONFIG"; then
+  { echo "$as_me:$LINENO: result: $ac_pt_PKG_CONFIG" >&5
+echo "${ECHO_T}$ac_pt_PKG_CONFIG" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+  if test "x$ac_pt_PKG_CONFIG" = x; then
+    PKG_CONFIG=""
+  else
+    case $cross_compiling:$ac_tool_warned in
+yes:)
+{ echo "$as_me:$LINENO: WARNING: In the future, Autoconf will not detect cross-tools
+whose name does not start with the host triplet.  If you think this
+configuration is useful to you, please write to autoconf@gnu.org." >&5
+echo "$as_me: WARNING: In the future, Autoconf will not detect cross-tools
+whose name does not start with the host triplet.  If you think this
+configuration is useful to you, please write to autoconf@gnu.org." >&2;}
+ac_tool_warned=yes ;;
+esac
+    PKG_CONFIG=$ac_pt_PKG_CONFIG
+  fi
+else
+  PKG_CONFIG="$ac_cv_path_PKG_CONFIG"
+fi
+
+fi
+if test -n "$PKG_CONFIG"; then
+	_pkg_min_version=0.9.0
+	{ echo "$as_me:$LINENO: checking pkg-config is at least version $_pkg_min_version" >&5
+echo $ECHO_N "checking pkg-config is at least version $_pkg_min_version... $ECHO_C" >&6; }
+	if $PKG_CONFIG --atleast-pkgconfig-version $_pkg_min_version; then
+		{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	else
+		{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+		PKG_CONFIG=""
+	fi
+
+fi
+
+
+pkg_failed=no
+{ echo "$as_me:$LINENO: checking for QT" >&5
+echo $ECHO_N "checking for QT... $ECHO_C" >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$QT_CFLAGS"; then
+        pkg_cv_QT_CFLAGS="$QT_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"QtGui >= 4.0.1\"") >&5
+  ($PKG_CONFIG --exists --print-errors "QtGui >= 4.0.1") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_QT_CFLAGS=`$PKG_CONFIG --cflags "QtGui >= 4.0.1" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$QT_LIBS"; then
+        pkg_cv_QT_LIBS="$QT_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"QtGui >= 4.0.1\"") >&5
+  ($PKG_CONFIG --exists --print-errors "QtGui >= 4.0.1") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_QT_LIBS=`$PKG_CONFIG --libs "QtGui >= 4.0.1" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        QT_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "QtGui >= 4.0.1"`
+        else
+	        QT_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "QtGui >= 4.0.1"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$QT_PKG_ERRORS" >&5
+
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+                { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+elif test $pkg_failed = untried; then
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+else
+	QT_CFLAGS=$pkg_cv_QT_CFLAGS
+	QT_LIBS=$pkg_cv_QT_LIBS
+        { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	qt4=yes
+fi
+
 	MOC="${e_qtmoc}"
 	# Extract the first word of "moc", so it can be a program name with args.
 set dummy moc; ac_word=$2
@@ -7332,54 +7531,84 @@ if test "${enable_fhs+set}" = set; then
 fi
 
 
-if test "$e_docdir" = "" ; then e_docdir="$docdir" ; fi
-if test "$e_docdir" = "" ; then e_docdir="$datadir/$PACKAGE/doc" ; fi
-
-if test "$e_initdir" = "" ; then e_initdir="$libexecdir/$PACKAGE/init" ; fi
-
-if test "$e_spooldir" = "" ; then e_spooldir="$localstatedir/spool/$PACKAGE" ; fi
-
-if test "$e_examplesdir" = "" ; then e_examplesdir="$libexecdir/$PACKAGE/examples" ; fi
-
-if test "$e_libexecdir" = "" ; then e_libexecdir="$libexecdir/$PACKAGE" ; fi
-
-if test "$e_sysconfdir" = "" ; then e_sysconfdir="$sysconfdir" ; fi
-
-if test "$e_qtmoc" = "" ; then e_qtmoc="moc" ; fi
-
 	if test "$enable_fhs" = "yes"
 	then
-
-	# tweaks for fhs compliance...
-	#
-	prefix='/usr'
-	exec_prefix='/usr'
-	#
-	sbindir='/usr/sbin'
-	libexecdir='/usr/lib'
-	localstatedir='/var'
-	mandir='/usr/share/man'
-	datadir='/usr/share'
-	sysconfdir='/etc'
-	#
-	# not used by emailrelay
-	#bindir=
-	#sharedstatedir=
-	#libdir=
-	#includedir=
-	#oldincludedir=
-	#infodir=
-	#
-	# emailrelay-specific
-	e_libexecdir="$libexecdir/$PACKAGE"
-	e_docdir="$datadir/doc/$PACKAGE"
-	e_initdir="/etc/init.d"
-	e_spooldir="$localstatedir/spool/$PACKAGE"
-	e_examplesdir="$libexecdir/$PACKAGE/examples"
-	e_sysconfdir="$sysconfdir"
-
+		prefix='/usr'
+		exec_prefix='/usr'
+		sbindir="/usr/sbin"
+		libexecdir="/usr/lib"
+		localstatedir="/var"
+		mandir="/usr/share/man"
+		datadir="/usr/share"
+		sysconfdir="/etc"
+	fi
+	if test "$e_docdir" = ""
+	then
+		if test "$enable_fhs" = "yes"
+		then
+			e_docdir="$datadir/doc/$PACKAGE"
+		else
+			e_docdir="$docdir"
+			if test "$e_docdir" = ""
+			then
+				e_docdir="$datadir/$PACKAGE/doc"
+			fi
+		fi
+	fi
+	if test "$e_initdir" = ""
+	then
+		if test "$enable_fhs" = "yes"
+		then
+			e_initdir="/etc/init.d"
+		else
+			e_initdir="$libexecdir/$PACKAGE/init"
+		fi
+	fi
+	if test "$e_spooldir" = ""
+	then
+		if test "$enable_fhs" = "yes"
+		then
+			e_spooldir="$localstatedir/spool/$PACKAGE"
+		else
+			e_spooldir="$localstatedir/spool/$PACKAGE"
+		fi
+	fi
+	if test "$e_examplesdir" = ""
+	then
+		if test "$enable_fhs" = "yes"
+		then
+			e_examplesdir="$libexecdir/$PACKAGE/examples"
+		else
+			e_examplesdir="$libexecdir/$PACKAGE/examples"
+		fi
+	fi
+	if test "$e_libexecdir" = ""
+	then
+		if test "$enable_fhs" = "yes"
+		then
+			e_libexecdir="$libexecdir/$PACKAGE"
+		else
+			e_libexecdir="$libexecdir/$PACKAGE"
+		fi
+	fi
+	if test "$e_sysconfdir" = ""
+	then
+		if test "$enable_fhs" = "yes"
+		then
+			e_sysconfdir="$sysconfdir"
+		else
+			e_sysconfdir="$sysconfdir"
+		fi
 	fi
 
+
+
+
+
+
+
+
+if test "$e_qtmoc" = "" ; then e_qtmoc="moc" ; fi
 
 ac_config_files="$ac_config_files Makefile src/Makefile src/glib/Makefile src/gssl/Makefile src/gnet/Makefile src/gsmtp/Makefile src/gpop/Makefile src/main/Makefile src/win32/Makefile src/gui/Makefile lib/Makefile lib/gcc2.95/Makefile lib/msvc6.0/Makefile bin/Makefile doc/Makefile etc/Makefile test/Makefile extra/Makefile extra/mips/Makefile src/fragments/Makefile"
 
@@ -8243,9 +8472,9 @@ HAVE_MAN2HTML!$HAVE_MAN2HTML$ac_delim
 COMPILER_VERSION!$COMPILER_VERSION$ac_delim
 CPP!$CPP$ac_delim
 EGREP!$EGREP$ac_delim
-MOC!$MOC$ac_delim
 PKG_CONFIG!$PKG_CONFIG$ac_delim
-IPV6_TRUE!$IPV6_TRUE$ac_delim
+QT_CFLAGS!$QT_CFLAGS$ac_delim
+QT_LIBS!$QT_LIBS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -8287,8 +8516,9 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+MOC!$MOC$ac_delim
+IPV6_TRUE!$IPV6_TRUE$ac_delim
 IPV6_FALSE!$IPV6_FALSE$ac_delim
-QT_LIBS!$QT_LIBS$ac_delim
 GUI_TRUE!$GUI_TRUE$ac_delim
 GUI_FALSE!$GUI_FALSE$ac_delim
 POP_TRUE!$POP_TRUE$ac_delim
@@ -8328,7 +8558,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 39; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 40; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
